apiVersion: v1
kind: Service
metadata:
  name: mysql-selvin
  namespace: capacitaciones
spec:
  clusterIP: None
  clusterIPs:
  - None
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql-selvin
  sessionAffinity: None
  type: ClusterIP