apiVersion: v1
kind: Pod
metadata:
  labels:
    app: mysql-selvin
    controller-revision-hash: mysql-selvin-8c49fc986
    statefulset.kubernetes.io/pod-name: mysql-selvin-1
  name: mysql-selvin-1
  namespace: capacitaciones
spec:
  containers:
  - env:
    - name: MYSQL_ROOT_PASSWORD
      value: password
    image: mysql:5.6
    imagePullPolicy: IfNotPresent
    name: mysql-selvin
    ports:
    - containerPort: 3306
      name: mysql-selvin
      protocol: TCP
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/lib/mysqllao
      name: data
      subPath: mysql-selvin
    - mountPath: /etc/mysqllao/conf.d
      name: conf
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-5bcc8
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostname: mysql-selvin-1
  nodeName: kubernetes-dev-cdc-master-01
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  subdomain: mysql-selvin
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: data-mysql-selvin-1
  - emptyDir: {}
    name: conf
  - configMap:
      defaultMode: 420
      name: mysql-selvin
    name: config-map
  - name: default-token-5bcc8
    secret:
      defaultMode: 420
      secretName: default-token-5bcc8