version: "3.8"

services:
  app:
    image: test-06:01
    environment:
      TZ: "America/Tegucigalpa"
      MONGO_URL: "mongodb://db:27017/test"
    depends_on:
      - db
    ports:
      - "3000:3000"

  db:
    image: mongo
